"""Create the .env file with fresh random keys and tokens (it is git-ignored).

    python scripts/new_env.py --demo     # demonstration model, no API keys needed
    python scripts/new_env.py            # live: Claude (add your ANTHROPIC_API_KEY) + Ollama

Every secret is random and local to this machine. In a real deployment they would come from a
secret store (for example Azure Key Vault) instead of a file.
"""

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def token(prefix: str) -> str:
    return f"{prefix}_{secrets.token_urlsafe(24)}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--demo", action="store_true", help="use the demonstration model")
    parser.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = parser.parse_args()

    path = ROOT / ".env"
    if path.exists() and not args.force:
        print(f"{path} already exists; use --force to replace it.", file=sys.stderr)
        return 1

    people = {
        "alice": ("requester", token("alice")),
        "bob": ("approver", token("bob")),
        "ops": ("admin", token("ops")),
    }
    lines = [
        "# Generated by scripts/new_env.py. Never commit this file.",
        f"GATEWAY_CONFIG={'gateway.demo.json' if args.demo else 'gateway.json'}",
        "",
        "# Team keys for the gateway (applications authenticate with these)",
        f"LLMGW_KEY_AGENTS={token('gw_agents')}",
        f"LLMGW_KEY_EVIDENCE={token('gw_evidence')}",
        f"LLMGW_KEY_RESEARCH={token('gw_research')}",
        "",
        "# People who use the agents service: name:role:token",
        "GOVAGENTS_API_TOKENS="
        + ",".join(f"{name}:{role}:{tok}" for name, (role, tok) in people.items()),
        "",
        "# Monitoring scrape tokens",
        f"GATEWAY_METRICS_TOKEN={token('metrics')}",
        f"AGENTS_METRICS_TOKEN={token('metrics')}",
        "",
        "# Live models only: your Anthropic key (leave empty for the demo)",
        "ANTHROPIC_API_KEY=",
        "",
        "# Where the component sources are (defaults: sibling folders)",
        "# GATEWAY_SRC=../governed-llm-gateway",
        "# EVIDENCE_SRC=../policy-evidence-mcp",
        "# AGENTS_SRC=../governed-agents",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {path}.")
    print("Sign in to the approvals page (http://127.0.0.1:8090) with one of these tokens:")
    for name, (role, tok) in people.items():
        print(f"  {name:<6} {role:<10} {tok}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
