"""Create the platform's secrets with fresh random keys and tokens (all git-ignored).

    python scripts/new_env.py --demo     # demonstration model, no API keys needed
    python scripts/new_env.py            # live: Claude (add your ANTHROPIC_API_KEY) + Ollama
    python scripts/new_env.py --sovereign   # open-weight models only: nothing leaves, no key
    add --tracing to send traces to the Jaeger of the `tracing` profile
    add --kubernetes to write the secrets of the matching Kubernetes overlay instead of .env
    --azure writes deploy/azure/secrets.env for the Bicep deployment (Azure OpenAI)

For Docker Compose it writes `.env` and `secrets/evidence-mcp-tokens.json`. With --kubernetes it
writes `deploy/kubernetes/overlays/<demo|live|sovereign>/secrets/`, which the overlay turns into
Kubernetes Secrets. Every secret is random and local to this machine; in a real deployment they
would come from a secret store (for example Azure Key Vault) instead of files.

The MCP evidence server receives only the SHA-256 hash of the agents service's token (the same
format as `evidence-mcp token create`), with the clearance "internal".
"""

import argparse
import hashlib
import json
import secrets
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAEGER_OTLP = "http://jaeger:4318"


def token(prefix: str) -> str:
    return f"{prefix}_{secrets.token_urlsafe(24)}"


def config_file(args: argparse.Namespace) -> str:
    if args.demo:
        return "gateway.demo.json"
    return "gateway.sovereign.json" if args.sovereign else "gateway.json"


def overlay(args: argparse.Namespace) -> str:
    return "demo" if args.demo else "sovereign" if args.sovereign else "live"


def evidence_tokens(agents_token: str) -> str:
    """The MCP server's token file: who may call it, with which clearance (hashes only)."""
    record = {
        "name": "agents-service",
        "clearance": "internal",
        "sha256": hashlib.sha256(agents_token.encode("utf-8")).hexdigest(),
        "created": time.strftime("%Y-%m-%d"),
    }
    return json.dumps([record], indent=2) + "\n"


def generate(args: argparse.Namespace) -> tuple[dict[str, str], dict[str, tuple[str, str]]]:
    people = {
        "alice": ("requester", token("alice")),
        "bob": ("approver", token("bob")),
        "ops": ("admin", token("ops")),
    }
    values = {
        "LLMGW_KEY_AGENTS": token("gw_agents"),
        "LLMGW_KEY_EVIDENCE": token("gw_evidence"),
        "LLMGW_KEY_RESEARCH": token("gw_research"),
        "GOVAGENTS_API_TOKENS": ",".join(
            f"{name}:{role}:{tok}" for name, (role, tok) in people.items()
        ),
        "EVIDENCE_MCP_TOKEN_AGENTS": token("emcp_agents"),
        "GATEWAY_METRICS_TOKEN": token("metrics"),
        "AGENTS_METRICS_TOKEN": token("metrics"),
        "ANTHROPIC_API_KEY": "",
    }
    return values, people


def write_compose(args, values: dict[str, str]) -> Path:
    lines = [
        "# Generated by scripts/new_env.py. Never commit this file.",
        f"GATEWAY_CONFIG={config_file(args)}",
        "",
        "# Team keys for the gateway (applications authenticate with these)",
        *(
            f"{k}={values[k]}"
            for k in ("LLMGW_KEY_AGENTS", "LLMGW_KEY_EVIDENCE", "LLMGW_KEY_RESEARCH")
        ),
        "",
        "# People who use the agents service: name:role:token",
        f"GOVAGENTS_API_TOKENS={values['GOVAGENTS_API_TOKENS']}",
        "",
        "# The agents service's token for the MCP evidence server (the server holds its hash)",
        f"EVIDENCE_MCP_TOKEN_AGENTS={values['EVIDENCE_MCP_TOKEN_AGENTS']}",
        "",
        "# Monitoring scrape tokens",
        f"GATEWAY_METRICS_TOKEN={values['GATEWAY_METRICS_TOKEN']}",
        f"AGENTS_METRICS_TOKEN={values['AGENTS_METRICS_TOKEN']}",
        "",
        "# Tracing: where the services send spans (empty: tracing off)",
        f"OTEL_EXPORTER_OTLP_ENDPOINT={JAEGER_OTLP if args.tracing else ''}",
        "",
        "# Live models only: your Anthropic key (leave empty for the demo and sovereign modes)",
        "ANTHROPIC_API_KEY=",
        "",
        "# Where the component sources are (defaults: sibling folders)",
        "# GATEWAY_SRC=../governed-llm-gateway",
        "# EVIDENCE_SRC=../policy-evidence-mcp",
        "# AGENTS_SRC=../governed-agents",
    ]
    path = ROOT / ".env"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tokens = ROOT / "secrets" / "evidence-mcp-tokens.json"
    tokens.parent.mkdir(exist_ok=True)
    tokens.write_text(evidence_tokens(values["EVIDENCE_MCP_TOKEN_AGENTS"]), encoding="utf-8")
    return path


def write_kubernetes(args, values: dict[str, str]) -> Path:
    folder = ROOT / "deploy" / "kubernetes" / "overlays" / overlay(args) / "secrets"
    folder.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/new_env.py --kubernetes. Never commit this file."]
    lines += [f"{k}={v}" for k, v in values.items()]
    (folder / "platform.env").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (folder / "evidence-mcp-tokens.json").write_text(
        evidence_tokens(values["EVIDENCE_MCP_TOKEN_AGENTS"]), encoding="utf-8"
    )
    return folder / "platform.env"


def write_azure(values: dict[str, str]) -> Path:
    """Environment variables read by deploy/azure/main.bicepparam (values in single quotes)."""
    path = ROOT / "deploy" / "azure" / "secrets.env"
    values = {k: v for k, v in values.items() if k != "ANTHROPIC_API_KEY"}
    values["EVIDENCE_MCP_TOKENS_JSON"] = json.dumps(
        json.loads(evidence_tokens(values["EVIDENCE_MCP_TOKEN_AGENTS"])), separators=(",", ":")
    )
    lines = ["# Generated by scripts/new_env.py --azure. Never commit this file."]
    lines += [f"{k}='{v}'" for k, v in values.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--demo", action="store_true", help="use the demonstration model")
    mode.add_argument(
        "--sovereign", action="store_true", help="open-weight models only, every team local_only"
    )
    parser.add_argument("--tracing", action="store_true", help="send traces to Jaeger")
    parser.add_argument(
        "--kubernetes", action="store_true", help="write the Kubernetes overlay's secrets"
    )
    parser.add_argument(
        "--azure", action="store_true", help="write deploy/azure/secrets.env for the Bicep"
    )
    parser.add_argument("--force", action="store_true", help="overwrite existing secrets")
    args = parser.parse_args()

    if args.azure:
        target = ROOT / "deploy" / "azure" / "secrets.env"
    elif args.kubernetes:
        target = ROOT / "deploy" / "kubernetes" / "overlays" / overlay(args) / "secrets"
        target = target / "platform.env"
    else:
        target = ROOT / ".env"
    if target.exists() and not args.force:
        print(f"{target} already exists; use --force to replace it.", file=sys.stderr)
        return 1

    values, people = generate(args)
    if args.azure:
        path = write_azure(values)
    elif args.kubernetes:
        path = write_kubernetes(args, values)
    else:
        path = write_compose(args, values)
    print(f"Wrote {path}.")
    print("Sign in to the approvals page with one of these tokens:")
    for name, (role, tok) in people.items():
        print(f"  {name:<6} {role:<10} {tok}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
